default:
    @just --list

check:
    cargo fmt -- --check
    cargo clippy --all-targets --all-features -- -D warnings

test:
    cargo test --all-features

wasm-setup:
    rustup target add wasm32-unknown-unknown

wasm-npm-pack:
    wasm-pack build --target bundler --release --out-dir pkg-npm -- --features wasm

wasm-vendor: wasm-npm-pack
    node scripts/vendor.mjs
