[package]
name = "migration"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
# External dependencies
sea-orm-migration.workspace = true
tokio.workspace = true
dotenvy.workspace = true
anyhow.workspace = true
