name: Engine build

on:
  push:
  pull_request:

jobs:
  build:
    name: Engine / build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ochimono-engine

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.98.1
        with:
          targets: wasm32-unknown-unknown

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "ochimono-engine -> target"

      - name: Release Build
        run: cargo build --release --locked

      - name: WASM build
        run: cargo build --release --locked --target wasm32-unknown-unknown --features wasm
